The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2025-02-14 08:33:58.366 UTC [43] LOG:  listening on IPv6 address "::1", port 5432
2025-02-14 08:33:58.366 UTC [43] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2025-02-14 08:33:58.368 UTC [43] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-02-14 08:33:58.377 UTC [44] LOG:  database system was shut down at 2025-02-14 08:33:58 UTC
2025-02-14 08:33:58.381 UTC [43] LOG:  database system is ready to accept connections
 done
server started
2025-02-14 08:33:58.552 UTC [66] FATAL:  role "johndoe" does not exist
CREATE DATABASE

CREATE ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2025-02-14 08:33:59.349 UTC [43] LOG:  received fast shutdown request
2025-02-14 08:33:59.350 UTC [43] LOG:  aborting any active transactions
2025-02-14 08:33:59.351 UTC [43] LOG:  worker process: logical replication launcher (PID 50) exited with exit code 1
2025-02-14 08:33:59.353 UTC [45] LOG:  shutting down
2025-02-14 08:33:59.370 UTC [43] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2025-02-14 08:33:59.461 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-02-14 08:33:59.461 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-02-14 08:33:59.464 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-02-14 08:33:59.471 UTC [77] LOG:  database system was shut down at 2025-02-14 08:33:59 UTC
2025-02-14 08:33:59.476 UTC [1] LOG:  database system is ready to accept connections
2025-02-14 08:34:01.476 UTC [85] ERROR:  relation "_prisma_migrations" does not exist at character 126
2025-02-14 08:34:01.476 UTC [85] STATEMENT:  SELECT "id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count" FROM "_prisma_migrations" ORDER BY "started_at" ASC
2025-02-14 08:34:01.835 UTC [85] ERROR:  syntax error at or near "WITH" at character 89
2025-02-14 08:34:01.835 UTC [85] STATEMENT:  DROP DATABASE IF EXISTS "prisma_migrate_shadow_db_b90289fe-d544-4ddf-91b7-398579af741a" WITH (FORCE)
2025-02-14 08:34:02.345 UTC [85] ERROR:  syntax error at or near "WITH" at character 89
2025-02-14 08:34:02.345 UTC [85] STATEMENT:  DROP DATABASE IF EXISTS "prisma_migrate_shadow_db_337720d8-0210-4454-8b72-1cc974fa05b6" WITH (FORCE)
2025-02-14 08:34:02.793 UTC [85] ERROR:  syntax error at or near "WITH" at character 89
2025-02-14 08:34:02.793 UTC [85] STATEMENT:  DROP DATABASE IF EXISTS "prisma_migrate_shadow_db_9395ea22-be72-4bb4-99e4-5d519dd6dc04" WITH (FORCE)
2025-02-14 08:34:03.233 UTC [85] ERROR:  syntax error at or near "WITH" at character 89
2025-02-14 08:34:03.233 UTC [85] STATEMENT:  DROP DATABASE IF EXISTS "prisma_migrate_shadow_db_091bee54-5cc9-4d53-8269-7a9e21e5e9be" WITH (FORCE)
